import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'To-do-list',
  description: 'Generated by create next app',
  icon: 'icons8-to-do-list-32.png',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="'icons8-to-do-list-32.png" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
