// app/layout.tsx
'use client';

import React from 'react';
import { ChakraProvider } from '@chakra-ui/react';
import { CacheProvider } from '@emotion/react';
import createCache from '@emotion/cache';
import { ReactNode } from 'react';

const cache = createCache({ key: 'css', prepend: true });

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon-to-do-list.png" />
        <title>To-do-list</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <CacheProvider value={cache}>
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
